[package]
name = "lyrch"
version = "0.1.0"
authors = ["Antonio Román <kyradiscord@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.6.3"
dotenv = "0.14.1"
postgres = { version = "0.15.2", features = ["with-chrono", "with-bit-vec", "with-serde_json"] }
chrono = "0.4.7"
bit-vec = "0.4.4"
serde_json = "1.0.40"
regex = "1.2.1"
lazy_static = "1.3.0"
